services:
  db:
    image: postgres
    restart: always
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: TACT_DB
    ports:
      - "5432:5432"
    volumes:
      - "./db_data_volume:/var/lib/postgresql/data"
    links:
      - server
  server:
    build: ./Server
    restart: always
    ports:
      - 8080:8080
    environment:
      - SERVER_APP_PORT=8080
      - NODE_ENV=development
      - DATABASE_HOST=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_PORT=5432
      - POSTGRES_DB=TACT_DB
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    restart: always
    environment:
      - REACT_APP_PORT=3000
    ports:
      - 3000:3000