apiVersion: v1
kind: Service
metadata:
  name: tact-server
  labels:
    app: tact-server
spec:
  ports:
  - port: 8080
    name: server
  clusterIP: None
  selector:
    app: tact-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tact-server
  labels:
    app: tact-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tact-server
  template:
    metadata:
      labels:
        app: tact-server
    spec:
      containers:
      - name: tact-server
        image: mkborland/tact-server:v0.2
        imagePullPolicy: Always
        env:
        - name: SERVER_APP_PORT
          value: '8080'
        - name: NODE_ENV
          value: development
        - name: DATABASE_HOST
          value: tact-db
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_DB
          value: TACT_DB
        ports:
        - containerPort: 8080
          name: server